[project]
name = "anki-card-creator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.38.45",
    "genanki>=0.13.1",
    "python-dotenv>=1.1.1",
    "tqdm>=4.67.1",
]
